import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisSmoothScroll from "./components/Lenis";
import {LocalFont} from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const myFont = LocalFont({
  src: './fonts/Sansumi-Regular.ttf',
  variable: '--font-sansumi',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${myFont.variable} h-full antialiased`}
    >
      <LenisSmoothScroll />
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
